Homebrew formula points to new GCS bucket
The AWS S3 bucket has been deprecated with the migration of the BOSH CLI
pipeline to the Cloud Foundry Foundation; it has been replaced by the
new GCS bucket.

This commit fixes installation problems by pointing to the new bucket.

Fixes during `brew install bosh-cli`:

```
Error: bosh-cli: Failed to download resource "bosh-cli"
Download failed: https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-7.5.3-darwin-arm64
```

Signed-off-by: Brian Cunnie <brian.cunnie@broadcom.com>